
/*
 * Click nbfs://SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog.PhieuXuatDialog;

import BUS.SachBUS;
import BUS.TacGiaBUS;
import DTO.SachDTO;
import DTO.TacGiaDTO;
import DTO.KhachHangDTO;
import BUS.KhachHangBUS;
import BUS.KhuyenMaiBUS;
import BUS.NhanVienBUS;
import BUS.ThongKeBUS;
import DTO.KhuyenMaiDTO;
import DTO.TaiKhoanDTO;
import GUI.WorkFrame;
import com.toedter.calendar.JDateChooser;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.List;
import java.util.Date;
import java.util.HashMap;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JList;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import GUI.Format.NumberFormatter;
import java.util.Comparator;

/**
 *
 * @author DELL
 */
public class PhieuXuatDialogAdd extends javax.swing.JPanel { 
    // Variables declaration - do not modify                     
    private JButton BtnXoaAllV2;
    private JButton btnSua;
    private JButton btnThemChiTiet;
    private JButton btnThemPhieu;
    private JButton btnXoaV2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JLabel lbChonSach;
    private JLabel lbDonGiaV2;
    private JLabel lbGiaBan;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbListBan;
    private javax.swing.JLabel lbNgayTao;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbSoLuongV2;
    private javax.swing.JLabel lbTenSachV2;
    private javax.swing.JLabel lbThanhTienV2;
    private javax.swing.JLabel lbThanhToan;
    private javax.swing.JLabel lbTimKhach;
    private javax.swing.JLabel lbTimSach;
    private javax.swing.JLabel lbTongTien;
    private JTable tableChonSach;
    private javax.swing.JTable tableListBan;
    private javax.swing.JTextField txfDonGiaV2;
    private javax.swing.JTextField txfGiaBan;
    private javax.swing.JTextField txfGiamGia;
    private javax.swing.JTextField txfKhachHang;
    private javax.swing.JTextField txfNhanVien;
    private javax.swing.JTextField txfSDT;
    private javax.swing.JTextField txfSoLuong;
    private javax.swing.JTextField txfSoLuongV2;
    private javax.swing.JTextField txfTenSachV2;
    private javax.swing.JTextField txfThanhTienV2;
    private javax.swing.JTextField txfThanhToan;
    private javax.swing.JTextField txfTimKhach;
    private javax.swing.JTextField txfTimSach;
    private javax.swing.JTextField txfTongTien;
    private javax.swing.JLabel lbTenKhuyenMai;
    private javax.swing.JLabel lbPhanTramGiam;
    private javax.swing.JTextField txfTenKhuyenMai;
    private javax.swing.JTextField txfPhanTramGiam;
    // End of variables declaration              
    private DefaultTableModel dataBook;
    private ArrayList<SachDTO> listSach;
    private TacGiaBUS tacgiaBUS = new TacGiaBUS();
    private DefaultListModel<String> dataSDT;
    private DefaultListModel<String> dataFullNameKH;
    private JList<String> listSDT;
    private JPopupMenu popupMenuSDT;
    private JPopupMenu popupMenuNameKH;
    private ArrayList<KhachHangDTO> listkh;
    private HashMap<String, String> hashMapKh;
    private DefaultTableModel dataBan;
    private TaiKhoanDTO taikhoan;
    private NhanVienBUS nvBUS=new NhanVienBUS();
    private KhuyenMaiBUS kmBUS;
    private ArrayList<KhuyenMaiDTO> listkm;
    /**
     * Creates new form test1
     */
    public PhieuXuatDialogAdd( ) { 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        lbNgayTao = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        lbTimKhach = new javax.swing.JLabel();
        txfTimKhach = new javax.swing.JTextField();
        lbNhanVien = new javax.swing.JLabel();
        txfNhanVien = new javax.swing.JTextField();
        lbKhachHang = new javax.swing.JLabel();
        txfKhachHang = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbTimSach = new javax.swing.JLabel();
        txfTimSach = new javax.swing.JTextField();
        lbChonSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChonSach = new javax.swing.JTable();
        lbSoLuong = new javax.swing.JLabel();
        txfSoLuong = new javax.swing.JTextField();
        lbGiaBan = new javax.swing.JLabel();
        txfGiaBan = new javax.swing.JTextField();
        btnThemChiTiet = createButton("Thêm chi tiết", new Color(76, 175, 80)); // Xánh lá chuối
        lbListBan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableListBan = new javax.swing.JTable();
        lbTongTien = new javax.swing.JLabel();
        txfTongTien = new javax.swing.JTextField();
        lbGiamGia = new javax.swing.JLabel();
        txfGiamGia = new javax.swing.JTextField();
        lbThanhToan = new javax.swing.JLabel();
        txfThanhToan = new javax.swing.JTextField();
        
        lbTenKhuyenMai = new javax.swing.JLabel();
        txfTenKhuyenMai = new javax.swing.JTextField();
        lbPhanTramGiam = new javax.swing.JLabel();
        txfPhanTramGiam = new javax.swing.JTextField();

        lbTenKhuyenMai.setText("Tên KM:");
        txfTenKhuyenMai.setEditable(false);

        lbPhanTramGiam.setText("Giảm (%):");
        txfPhanTramGiam.setEditable(false);
       
        btnThemPhieu = createButton("Thêm phiếu", new Color(76, 175, 80)); // Xánh lá chuối
        btnSua = createButton("Sửa", new Color(255,191,0)); // Vàng
        jSeparator3 = new javax.swing.JSeparator();
        lbTenSachV2 = new javax.swing.JLabel();
        txfTenSachV2 = new javax.swing.JTextField();
        lbSoLuongV2 = new javax.swing.JLabel();
        txfSoLuongV2 = new javax.swing.JTextField();
        lbDonGiaV2 = new javax.swing.JLabel();
        txfDonGiaV2 = new javax.swing.JTextField();
        lbThanhTienV2 = new javax.swing.JLabel();
        txfThanhTienV2 = new javax.swing.JTextField();
        btnXoaV2 = createButton("Xóa", new Color(244, 67, 54)); // Màu đỏ
        BtnXoaAllV2 = createButton("Làm mới", new Color(72, 118, 255));
        lbSDT = new javax.swing.JLabel();
        txfSDT = new javax.swing.JTextField();

        lbNgayTao.setText("Ngày tạo:");
        
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        lbTimKhach.setText("Tìm khách:");
         // Gọi hàm lấy full SDT khách
        dataSDT = new DefaultListModel<>();
        listSDT = new JList<>(dataSDT);
        popupMenuSDT = new JPopupMenu();
        ArrayList<String> dsSDT = new KhachHangBUS().getAllSDT();
        for (String sdt : dsSDT) {
            dataSDT.addElement(sdt);
        }
        ArrayList<String> dsNameFull = new KhachHangBUS().getFullNameKH();
        for(String namekh: dsNameFull){
            dataSDT.addElement(namekh);
        }

        
        lbNhanVien.setText("Nhân viên:");

        txfNhanVien.setEditable(false);
        txfNhanVien.setToolTipText("");
        txfNhanVien.setText(nvBUS.getHoTenNVById(WorkFrame.taiKhoan.getManv()));
        
        lbKhachHang.setText("Khách hàng:");
        txfKhachHang.setEditable(false);
        // Dùng HasMap để hiện ra các MenuItems ở txf tìm khách
        listkh = new KhachHangBUS().getKhachHangAll();
        hashMapKh = new HashMap<String, String>();
        for (KhachHangDTO kh : listkh) {
            hashMapKh.put(kh.getSdt(), kh.getHokh() + " " + kh.getTenkh());
            hashMapKh.put(kh.getHokh() + " " + kh.getTenkh(), kh.getSdt());
        }

        lbTimSach.setText("Tìm sách:");

        lbChonSach.setFont(new java.awt.Font("Segoe UI", 0, 24));
        lbChonSach.setText("Chọn sách");
        lbChonSach.setHorizontalAlignment(javax.swing.JLabel.CENTER);

        String[] columnBook = {"Mã sách", "Tên sách", "Tên tác giả", "Số lượng tồn"};
        dataBook = new DefaultTableModel(columnBook, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        listSach = new SachBUS().getSachAll();
        listSach.sort(Comparator.comparingInt(s -> Integer.parseInt(s.getMasach().substring(1))));
        tacgiaBUS = new TacGiaBUS();
        tableChonSach = new JTable(dataBook);
        tableChonSach.getTableHeader().setReorderingAllowed(false);
        tableChonSach.getTableHeader().setBackground(Color.LIGHT_GRAY);
        tableChonSach.getTableHeader().setForeground(Color.BLACK);
        for (SachDTO s : listSach) {
            String TG = "";
            TacGiaDTO tg = tacgiaBUS.getTGById(s.getMatacgia());
            TG = tg.getHotentacgia();
            dataBook.addRow(new Object[]{s.getMasach(), s.getTensach(), TG, 
                NumberFormatter.format(s.getSoluongton())});
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int[] columnsToCenter = {0, 1, 2, 3};
        for (int col : columnsToCenter) {
            tableChonSach.getColumnModel().getColumn(col).setCellRenderer(centerRenderer);
        }
        
        tableChonSach.setRowHeight(30);
        tableChonSach.getColumnModel().getColumn(0).setPreferredWidth(35);
        tableChonSach.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableChonSach.getColumnModel().getColumn(2).setPreferredWidth(150);
        tableChonSach.getColumnModel().getColumn(3).setPreferredWidth(70);
        jScrollPane1.setViewportView(tableChonSach);

        lbSoLuong.setText("Số lượng:");

        lbGiaBan.setText("Giá bán:");

        txfGiaBan.setEditable(false);

        btnThemChiTiet.setText("Thêm chi tiết");
        btnThemChiTiet.setFont(new Font("Arial", Font.BOLD, 24));
        btnThemChiTiet.setPreferredSize(new Dimension(200, 46));

        lbListBan.setFont(new java.awt.Font("Segoe UI", 0, 24));
        lbListBan.setText("Danh sách bán");

        String[] columnListBan = {"Tên sách", "Số lượng", "Đơn giá", "Tổng"};
        dataBan = new DefaultTableModel(columnListBan, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableListBan = new JTable(dataBan);
        
        tableListBan.setRowHeight(30);
        tableListBan.getColumnModel().getColumn(0).setPreferredWidth(200);
        tableListBan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableListBan.getColumnModel().getColumn(2).setPreferredWidth(90);
        tableListBan.getColumnModel().getColumn(3).setPreferredWidth(130);
        DefaultTableCellRenderer centerRenderer1 = new DefaultTableCellRenderer();
        centerRenderer1.setHorizontalAlignment(JLabel.CENTER);
        int[] columnsToCenter1 = {0, 1, 2, 3};
        for (int col : columnsToCenter1) {
            tableListBan.getColumnModel().getColumn(col).setCellRenderer(centerRenderer1);
        }
        tableListBan.getTableHeader().setReorderingAllowed(false);
        tableListBan.getTableHeader().setBackground(Color.LIGHT_GRAY);
        tableListBan.getTableHeader().setForeground(Color.BLACK);
        jScrollPane2.setViewportView(tableListBan);

        lbTongTien.setText("Tổng tiền:");

        txfTongTien.setEditable(false);

        lbGiamGia.setText("Giảm giá:");
        txfGiamGia.setEditable(false);
        
        lbThanhToan.setText("Thanh toán:");

        txfThanhToan.setEditable(false);

        btnThemPhieu.setText("Thêm phiếu");
        btnThemPhieu.setPreferredSize(new Dimension(100, 34));
        btnThemPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.setPreferredSize(new Dimension(110, 34));

        btnXoaV2.setText("Xóa");
        btnXoaV2.setPreferredSize(new Dimension(110, 34));

        BtnXoaAllV2.setText("Làm mới");
        BtnXoaAllV2.setPreferredSize(new Dimension(110, 34));

        lbTenSachV2.setText("Tên sách:");

        txfTenSachV2.setEditable(false);

        lbSoLuongV2.setText("Số lượng");

        txfSoLuongV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSoLuongV2ActionPerformed(evt);
            }
        });

        lbDonGiaV2.setText("Đơn giá:");

        txfDonGiaV2.setEditable(false);

        lbThanhTienV2.setText("Thành tiền:");

        txfThanhTienV2.setEditable(false);

        lbSDT.setText("SDT:");

        txfSDT.setEditable(false);
        txfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNhanVien)
                                    .addComponent(lbNgayTao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txfNhanVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTimKhach)
                                    .addComponent(lbKhachHang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfTimKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbSDT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lbTimSach)
                                .addGap(18, 18, 18)
                                .addComponent(txfTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSoLuong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(242, 242, 242)
                                .addComponent(lbGiaBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(lbChonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnThemPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(btnXoaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(BtnXoaAllV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenKhuyenMai)
                            .addComponent(lbPhanTramGiam))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfTenKhuyenMai, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txfPhanTramGiam))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbTongTien)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbGiamGia)
                                    .addGap(12, 12, 12)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbThanhToan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txfGiamGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txfTongTien, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(7, 7, 7))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbListBan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenSachV2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDonGiaV2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfDonGiaV2)
                            .addComponent(txfTenSachV2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbThanhTienV2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfThanhTienV2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSoLuongV2)
                                .addGap(24, 24, 24)
                                .addComponent(txfSoLuongV2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15)))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbTimKhach)
                                    .addComponent(txfTimKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lbNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbNhanVien)
                                .addComponent(txfNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbKhachHang)
                                .addComponent(txfKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbSDT)
                                .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txfTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTimSach))
                            .addGap(11, 11, 11)
                            .addComponent(lbChonSach, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbSoLuong)
                                .addComponent(txfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbGiaBan)
                                .addComponent(txfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(lbListBan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTenSachV2)
                                .addComponent(txfTenSachV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbSoLuongV2)
                                .addComponent(txfSoLuongV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbDonGiaV2)
                                    .addComponent(txfDonGiaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbThanhTienV2)
                                    .addComponent(txfThanhTienV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTenKhuyenMai)
                                .addComponent(txfTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbTongTien)
                                .addComponent(txfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbPhanTramGiam)
                                .addComponent(txfPhanTramGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbGiamGia)
                                .addComponent(txfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbThanhToan)
                                .addComponent(txfThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnThemPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnXoaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnXoaAllV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, 0))
        );

        DocumentListener document = new PhieuXuatDialogAdd_Controller(this);
        txfTimKhach.getDocument().addDocumentListener(document);
        txfTimSach.getDocument().addDocumentListener(document);
        txfGiamGia.getDocument().addDocumentListener(document);

        ListSelectionListener selection = new PhieuXuatDialogAdd_Controller(this);
        tableChonSach.getSelectionModel().addListSelectionListener(selection);
        tableChonSach.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableListBan.getSelectionModel().addListSelectionListener(selection);
        tableListBan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        ActionListener action = new PhieuXuatDialogAdd_Controller(this);
        btnThemChiTiet.addActionListener(action);
        btnSua.addActionListener(action);
        btnXoaV2.addActionListener(action);
        BtnXoaAllV2.addActionListener(action);
        btnThemPhieu.addActionListener(action);
        // Cài đặt định dạng
        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.setDate(new Date());
    }
    
    private void btnThemPhieuActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txfSoLuongV2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txfTimKhachActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txfNhanVienActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txfSDTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }  

    public String getTxfTimSachText() {
        return txfTimSach.getText();
    }
    public JTextField getTxfTimKhach() {
        return txfTimKhach;
    }
    public JTextField getTxfTimSach() {
        return txfTimSach;
    }
    public void setTxfDonGia(String giaban) {
        this.txfGiaBan.setText(giaban);
    }
    public JTable getTableChonSach() {
        return tableChonSach;
    }
    public JTextField getTxfKhachHang() {
        return txfKhachHang;
    }
    public JTextField getTxtSoLuong() {
        return txfSoLuong;
    }
    public JTextField gettTxfDonGia() {
        return txfGiaBan;
    }
    public DefaultTableModel getDataBan() {
        return dataBan;
    }
    public JTable getTableListBan() {
        return tableListBan;
    }
    public JTextField getTxfTenSachV2() {
        return txfTenSachV2;
    }
    public JTextField getTxfSoLuongV2() {
        return txfSoLuongV2;
    }
    public JTextField getTxfDonGiaV2() {
        return txfDonGiaV2;
    }
    public JTextField getTxfThanhTienV2() {
        return txfThanhTienV2;
    }
    public JTextField getTxfTongTien() {
        return txfTongTien;
    }
    public JTextField getTxfGiamGia() {
        return txfGiamGia;
    }
    public JTextField getTxfThanhToan() {
        return txfThanhToan;
    }

    public void setTxfGiamGia(JTextField txfGiamGia) {
        this.txfGiamGia = txfGiamGia;
    }

    public void setTxfThanhToan(JTextField txfThanhToan) {
        this.txfThanhToan = txfThanhToan;
    }

    public void setTxfTongTien(JTextField txfTongTien) {
        this.txfTongTien = txfTongTien;
    }

    public JTextField getTxfSoLuong() {
        return txfSoLuong;
    }
    
    public JTextField getTxfNhanVien() {
        return txfNhanVien;
    }
    public JDateChooser getDateChooser1() {
        return jDateChooser1;
    }
    public JTextField getTxfSDT() {
        return txfSDT;
    }
    // Hàm tạo Button với hiệu ứng và màu sắc tùy chỉnh
    private JButton createButton(String text, Color bgColor) {
        JButton button = new JButton(text) {
            @Override
            protected void paintComponent(Graphics g) {
                Graphics2D g2 = (Graphics2D) g.create();
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // Xác định màu nền dựa trên trạng thái của button
                Color actualBgColor = bgColor;
                if (getModel().isPressed()) {
                    actualBgColor = bgColor.darker();
                } else if (getModel().isRollover()) {
                    actualBgColor = bgColor.brighter();
                }

                g2.setColor(actualBgColor);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15);

                super.paintComponent(g2);
                g2.dispose();
            }

            @Override
            protected void paintBorder(Graphics g) {
                // Không vẽ border mặc định
            }
        };

        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);
        button.setForeground(Color.WHITE);
        button.setFont(new Font("Arial", Font.BOLD, 12));

        return button;
    }
    
    // Show các số điện thoại
    public void ShowSDT() {
        popupMenuSDT.setVisible(false); // Ẩn popup trước khi cập nhật
        popupMenuSDT.removeAll();
        String input = txfTimKhach.getText();
        if (input.isEmpty()) return; // Không hiển thị nếu không có input
        boolean find = false;
        for (int i = 0; i < dataSDT.getSize(); i++) { // Duyệt qua DefaultListModel
            String phone = dataSDT.getElementAt(i);
            if (phone.startsWith(input)) {
                JMenuItem item = new JMenuItem(phone);
                item.addActionListener(e -> {
                    txfTimKhach.setText(phone); // Chọn số vào text field
                    popupMenuSDT.setVisible(false);
                });
                popupMenuSDT.add(item);
                find = true;
            }
        }
        if (find) {
            popupMenuSDT.show(txfTimKhach, 0, txfTimKhach.getHeight());
            if (txfTimKhach.isFocusOwner()) {
                SwingUtilities.invokeLater(() -> txfTimKhach.requestFocusInWindow());
            }
        }
    } 
    // Nhập SDT hoặc Tên xong nó hiện thông tin
    public void showNameKhandSDT() {
        String input = txfTimKhach.getText().trim();
        boolean check=false; // Nếu nó là sdt thì set khách hàng rồi set sdt
        if (hashMapKh.containsKey(input)) {
            for (char c: input.toCharArray()){
                if(!Character.isDigit(c)){
                    break;
                }
                check=true; // Nếu là True set 1 kiểu dữ liệu trong hashmap và nược lại
            }
            if(check){
                txfKhachHang.setText(hashMapKh.get(input));
                txfSDT.setText(input);
            }else{
                txfKhachHang.setText(input);
                txfSDT.setText(hashMapKh.get(input));
            }
            
        }
    }
        
    // Tìm sách bằng Document
    public void FindBook(String text) {
        listSach = new SachBUS().search(text);
        dataBook.setRowCount(0);
        for (SachDTO s : listSach) {
            String tentg = "";
            TacGiaDTO tg = tacgiaBUS.getTGById(s.getMatacgia());
            tentg = tg.getHotentacgia();
            dataBook.addRow(new Object[]{s.getMasach(), s.getTensach(), tentg, s.getSoluongton()});
        }
    }
    

    public void CalcBill(){
        kmBUS=new KhuyenMaiBUS();
        Date dateCreateBill= jDateChooser1.getDate();
        int tongTien = 0;
        int columnTong = 3;
        for(int i=0;i<tableListBan.getRowCount();i++){
             String value = tableListBan.getValueAt(i, columnTong).toString().trim();
             tongTien+=Integer.parseInt(NumberFormatter.formatReverse(value));
        }
        KhuyenMaiDTO bestKM= kmBUS.getBestKm(tongTien, dateCreateBill);
        double giamGia=(bestKM!=null) ? bestKM.getPhanTramGiam() : 0.0;
        double thanhtoan= tongTien - tongTien*giamGia/100;
        
        txfTongTien.setText(NumberFormatter.format(tongTien));
        txfGiamGia.setText(NumberFormatter.format(tongTien*giamGia/100));
        txfThanhToan.setText(NumberFormatter.format(thanhtoan));
        
        if(bestKM !=null){
             txfTenKhuyenMai.setText(bestKM.getTenChuongTrinh());
             txfPhanTramGiam.setText(bestKM.getPhanTramGiam()+"");
        }else{
             txfTenKhuyenMai.setText("");
             txfPhanTramGiam.setText("");
        }
   
        
    }

    public boolean CheckEmptyRow() {
        if (tableListBan.getRowCount() == 0) {
            return true;
        }
        return false;
    }

    public void setUpBlock(Boolean TorF){  // Truyền tham số True or False
        txfGiamGia.setEditable(TorF);
        txfTimKhach.setEditable(TorF);
        txfTimSach.setEditable(TorF);
        txfSoLuong.setEditable(TorF);
        txfSoLuongV2.setEditable(TorF);
        // Khóa các nút
        btnThemPhieu.setEnabled(TorF);
        btnSua.setEnabled(TorF);
        btnThemChiTiet.setEnabled(TorF);
        btnXoaV2.setEnabled(TorF);
        
    }
    
    public void setUpDefault() {
        SwingUtilities.invokeLater(() -> {
            // Đặt lại tất cả JTextField
            txfGiaBan.setText("");
            txfTongTien.setText("");
            txfGiamGia.setText("");
            txfThanhToan.setText("");
            txfKhachHang.setText("");
            txfSDT.setText("");
            txfTimKhach.setText("");
            txfTimSach.setText("");
            txfSoLuong.setText("");
            txfTenSachV2.setText("");
            txfSoLuongV2.setText("");
            txfDonGiaV2.setText("");
            txfThanhTienV2.setText("");
            txfTenKhuyenMai.setText("");
            txfPhanTramGiam.setText("");
            // Xóa bảng tableListBan
            dataBan.setRowCount(0);
            // Đặt lại ngày mặc định (tùy chọn)
            jDateChooser1.setDate(new Date());
            // Gọi CalcBill để đảm bảo giao diện nhất quán
//            CalcBill();
        });
    }

    public void refreshTableChonSach(){
        listSach=new SachBUS().getSachAll();
        listSach.sort(Comparator.comparingInt(s -> Integer.parseInt(s.getMasach().substring(1))));
        dataBook.setRowCount(0);
        for (SachDTO s : listSach) {
            String TG = "";
            TacGiaDTO tg = tacgiaBUS.getTGById(s.getMatacgia());
            TG = tg.getHotentacgia();
            dataBook.addRow(new Object[]{s.getMasach(), s.getTensach(), TG, s.getSoluongton()});
        }
    }

    void setTxfTongTien(String string) {
       this.txfTongTien.setText(string);
    }

    void setTxfGiamGia(String string) {
        this.txfGiamGia.setText(string);
    }

    void setTxfThanhToan(String string) {
        this.txfThanhToan.setText(string);
    }

    void setTxfTenKhuyenMai(String string) {
        this.txfTenKhuyenMai.setText(string);
    }

    void setTxfPhanTramGiam(String string) {
        this.txfPhanTramGiam.setText(string);
    }

    public JTextField getTxfTenKhuyenMai() {
        return txfTenKhuyenMai;
    }

    public JTextField getTxfPhanTramGiam() {
        return txfPhanTramGiam;
    }
    
    
}