/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.Dialog.PhieuXuatDialog;
import BUS.SachBUS;
import BUS.TacGiaBUS;
import DTO.SachDTO;
import DTO.TacGiaDTO;
import DTO.KhachHangDTO;
import BUS.KhachHangBUS;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.JList;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;


/**
 *
 * @author DELL
 */
public class PhieuXuatDialogAdd extends javax.swing.JDialog {
    // Variables declaration - do not modify                     
    private JButton BtnXoaAllV2;
    private JButton btnSua;
    private JButton btnThemChiTiet;
    private JButton btnThemPhieu;
    private JButton btnXoaV2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JSeparator jSeparator1;
    private JSeparator jSeparator2;
    private JSeparator jSeparator3;
    private JLabel lbChonSach;
    private JLabel lbDonGiaV2;
    private JLabel lbGiaBan;
    private javax.swing.JLabel lbGiamGia;
    private javax.swing.JLabel lbKhachHang;
    private javax.swing.JLabel lbListBan;
    private javax.swing.JLabel lbNgayTao;
    private javax.swing.JLabel lbNhanVien;
    private javax.swing.JLabel lbSDT;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbSoLuongV2;
    private javax.swing.JLabel lbTenSachV2;
    private javax.swing.JLabel lbThanhTienV2;
    private javax.swing.JLabel lbThanhToan;
    private javax.swing.JLabel lbTimKhach;
    private javax.swing.JLabel lbTimSach;
    private javax.swing.JLabel lbTongTien;
    private JTable tableChonSach;
    private javax.swing.JTable tableListBan;
    private javax.swing.JTextField txfDonGiaV2;
    private javax.swing.JTextField txfGiaBan;
    private javax.swing.JTextField txfGiamGia;
    private javax.swing.JTextField txfKhachHang;
    private javax.swing.JTextField txfNhanVien;
    private javax.swing.JTextField txfSDT;
    private javax.swing.JTextField txfSoLuong;
    private javax.swing.JTextField txfSoLuongV2;
    private javax.swing.JTextField txfTenSachV2;
    private javax.swing.JTextField txfThanhTienV2;
    private javax.swing.JTextField txfThanhToan;
    private javax.swing.JTextField txfTimKhach;
    private javax.swing.JTextField txfTimSach;
    private javax.swing.JTextField txfTongTien;
    // End of variables declaration              
    private DefaultTableModel dataBook;
    private ArrayList<SachDTO> listSach;
    private TacGiaBUS tacgiaBUS =new TacGiaBUS();
    private DefaultListModel<String> dataSDT;
    private JList<String> listSDT;
    private JPopupMenu popupMenuSDT;
    private ArrayList<KhachHangDTO> listkh;
    private HashMap<String, String> hashMapKh;
    private DefaultTableModel dataBan;
    

    /**
     * Creates new form test1
     */
    public PhieuXuatDialogAdd(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbNgayTao = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jSeparator1 = new javax.swing.JSeparator();
        lbTimKhach = new javax.swing.JLabel();
        txfTimKhach = new javax.swing.JTextField();
        lbNhanVien = new javax.swing.JLabel();
        txfNhanVien = new javax.swing.JTextField();
        lbKhachHang = new javax.swing.JLabel();
        txfKhachHang = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbTimSach = new javax.swing.JLabel();
        txfTimSach = new javax.swing.JTextField();
        lbChonSach = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChonSach = new javax.swing.JTable();
        lbSoLuong = new javax.swing.JLabel();
        txfSoLuong = new javax.swing.JTextField();
        lbGiaBan = new javax.swing.JLabel();
        txfGiaBan = new javax.swing.JTextField();
        btnThemChiTiet = new javax.swing.JButton();
        lbListBan = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableListBan = new javax.swing.JTable();
        lbTongTien = new javax.swing.JLabel();
        txfTongTien = new javax.swing.JTextField();
        lbGiamGia = new javax.swing.JLabel();
        txfGiamGia = new javax.swing.JTextField();
        lbThanhToan = new javax.swing.JLabel();
        txfThanhToan = new javax.swing.JTextField();
        btnThemPhieu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        lbTenSachV2 = new javax.swing.JLabel();
        txfTenSachV2 = new javax.swing.JTextField();
        lbSoLuongV2 = new javax.swing.JLabel();
        txfSoLuongV2 = new javax.swing.JTextField();
        lbDonGiaV2 = new javax.swing.JLabel();
        txfDonGiaV2 = new javax.swing.JTextField();
        lbThanhTienV2 = new javax.swing.JLabel();
        txfThanhTienV2 = new javax.swing.JTextField();
        btnXoaV2 = new javax.swing.JButton();
        BtnXoaAllV2 = new javax.swing.JButton();
        lbSDT = new javax.swing.JLabel();
        txfSDT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbNgayTao.setText("Ngày tạo:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        // Tìm khách theo số điện thoại
        lbTimKhach.setText("Tìm khách:");

        txfTimKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTimKhachActionPerformed(evt);
            }
        });
        dataSDT=new DefaultListModel<>();
        listSDT=new JList<>(dataSDT);
        popupMenuSDT=new JPopupMenu();
        ArrayList<String> dsSDT=new KhachHangBUS().getAllSDT();
        for(String sdt: dsSDT){
            dataSDT.addElement(sdt);
        }
        //-----------------------------------------------------------------------------------------------------

        lbNhanVien.setText("Nhân viên:");

        txfNhanVien.setEditable(false);
        txfNhanVien.setToolTipText("");
        txfNhanVien.setText("Nguyễn Tiến Trung");
        txfNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNhanVienActionPerformed(evt);
            }
        });
        //-----------------------------------------------------------------------------------------------------
        
        lbKhachHang.setText("Khách hàng:");
        txfKhachHang.setEditable(false);
        listkh= new KhachHangBUS().getKhachHangAll();
        hashMapKh=new HashMap<String,String>();
        for (KhachHangDTO kh: listkh){
            hashMapKh.put(kh.getSdt(), kh.getHokh()+" "+kh.getTenkh());
        }

        //-----------------------------------------------------------------------------------------------------
        lbTimSach.setText("Tìm sách:");

        lbChonSach.setText("Chọn sách");
        //-----------------------------------------------------------------------------------------------------
        // Table của phần chọn sách
        String[] columnBook={"Mã sách","Tên sách","Tên tác giả","Số lượng tồn"};
        dataBook =new DefaultTableModel(columnBook,0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Chặn chỉnh sửa tất cả các ô
            }
        };
        listSach=new SachBUS().getSachAll(); // Truyền list  sách vào
        tacgiaBUS=new TacGiaBUS();           // Tạo biến TacGiaBUS
        tableChonSach=new JTable(dataBook);
        tableChonSach.getTableHeader().setReorderingAllowed(false); // Ngăn di chuyển giữa các cột
        tableChonSach.getTableHeader().setBackground(Color.LIGHT_GRAY);
        tableChonSach.getTableHeader().setForeground(Color.BLACK); // Màu chữ đen
        for (SachDTO s: listSach){
            String TG="";
            TacGiaDTO tg=tacgiaBUS.getTGById(s.getMatacgia());
            TG=tg.getHotentacgia();
            dataBook.addRow(new Object[]{s.getMasach(),s.getTensach(),TG,s.getSoluongton()});
        }
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int[] columnsToCenter = {0 , 1,2,3}; // Căn giữa tất cả trừ tên sách và tên nbx
        for (int col : columnsToCenter) {
            tableChonSach.getColumnModel().getColumn(col).setCellRenderer(centerRenderer);
        }
        tableChonSach.setRowHeight(30);
        tableChonSach.getColumnModel().getColumn(0).setPreferredWidth(35);
        tableChonSach.getColumnModel().getColumn(1).setPreferredWidth(200);
        tableChonSach.getColumnModel().getColumn(2).setPreferredWidth(150);
        tableChonSach.getColumnModel().getColumn(3).setPreferredWidth(70);
        jScrollPane1.setViewportView(tableChonSach);
        
        //-----------------------------------------------------------------------------------------------------
        lbSoLuong.setText("Số lượng:");

//        txfSoLuong.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txfSoLuongActionPerformed(evt);
//            }
//        });

        lbGiaBan.setText("Giá bán:");

        txfGiaBan.setEditable(false);
//        txfGiaBan.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txfGiaBanActionPerformed(evt);
//            }
//        });

        btnThemChiTiet.setText("Thêm");

        lbListBan.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbListBan.setText("Danh sách bán");
        
        //-----------------------------------------------------------------------------------------------------
        
        String[] columnListBan={"Tên sách","Số lượng","Đơn giá","Tổng"};
        dataBan=new DefaultTableModel(columnListBan,0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Chặn chỉnh sửa tất cả các ô
            }
        };
        tableListBan=new JTable(dataBan);
        tableListBan.setRowHeight(30);
        tableListBan.getColumnModel().getColumn(0).setPreferredWidth(200);
        tableListBan.getColumnModel().getColumn(1).setPreferredWidth(100);
        tableListBan.getColumnModel().getColumn(2).setPreferredWidth(90);
        tableListBan.getColumnModel().getColumn(3).setPreferredWidth(130);
        DefaultTableCellRenderer centerRenderer1 = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        int[] columnsToCenter1 = {0 , 1,2,3}; // Căn giữa tất cả trừ tên sách và tên nbx
        for (int col : columnsToCenter) {
            tableListBan.getColumnModel().getColumn(col).setCellRenderer(centerRenderer);
        }
        tableListBan.getTableHeader().setReorderingAllowed(false); // Ngăn di chuyển giữa các cột
        tableListBan.getTableHeader().setBackground(Color.LIGHT_GRAY);
        tableListBan.getTableHeader().setForeground(Color.BLACK); // Màu chữ đen
        jScrollPane2.setViewportView(tableListBan);

        lbTongTien.setText("Tổng tiền:");

        txfTongTien.setEditable(false);

        lbGiamGia.setText("Giảm giá:");

        lbThanhToan.setText("Thanh toán:");

        txfThanhToan.setEditable(false);

        btnThemPhieu.setText("Thêm phiếu");
        btnThemPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemPhieuActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");

        lbTenSachV2.setText("Tên sách:");

        txfTenSachV2.setEditable(false);

        lbSoLuongV2.setText("Số lượng");
        

        txfSoLuongV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSoLuongV2ActionPerformed(evt);
            }
        });
        
        lbDonGiaV2.setText("Đơn giá:");

        txfDonGiaV2.setEditable(false);

        lbThanhTienV2.setText("Thành tiền:");

        txfThanhTienV2.setEditable(false);

        btnXoaV2.setText("Xóa");

        BtnXoaAllV2.setText("Xóa tất cả");

        lbSDT.setText("SDT:");

        txfSDT.setEditable(false);
        txfSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSDTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addComponent(lbNhanVien))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(lbNgayTao)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txfNhanVien))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbTimKhach)
                                    .addComponent(lbKhachHang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfTimKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbSDT)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addComponent(lbTimSach)
                                .addGap(18, 18, 18)
                                .addComponent(txfTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbChonSach)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbSoLuong)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addComponent(lbGiaBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addGap(38, 38, 38)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThemPhieu)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtnXoaAllV2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbTongTien)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbGiamGia)
                                    .addGap(12, 12, 12)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbThanhToan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txfThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txfGiamGia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(txfTongTien, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(7, 7, 7))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbListBan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbTenSachV2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDonGiaV2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfDonGiaV2)
                            .addComponent(txfTenSachV2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbThanhTienV2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txfThanhTienV2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbSoLuongV2)
                                .addGap(24, 24, 24)
                                .addComponent(txfSoLuongV2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbTimKhach)
                                .addComponent(txfTimKhach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNhanVien)
                            .addComponent(txfNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbKhachHang)
                            .addComponent(txfKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSDT)
                            .addComponent(txfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfTimSach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTimSach))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbChonSach)
                                .addGap(98, 98, 98)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSoLuong)
                            .addComponent(txfSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbGiaBan))
                        .addGap(18, 18, 18)
                        .addComponent(btnThemChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lbListBan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenSachV2)
                            .addComponent(txfTenSachV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSoLuongV2)
                            .addComponent(txfSoLuongV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbDonGiaV2)
                                .addComponent(txfDonGiaV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbThanhTienV2)
                                .addComponent(txfThanhTienV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTongTien)
                            .addComponent(txfTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbGiamGia)
                            .addComponent(txfGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbThanhToan)
                            .addComponent(txfThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaV2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnXoaAllV2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DocumentListener document=new PhieuXuatDialogAdd_Controller(this);
        txfTimKhach.getDocument().addDocumentListener(document);
        txfTimSach.getDocument().addDocumentListener(document);
        txfGiamGia.getDocument().addDocumentListener(document);
        
        ListSelectionListener selection=new PhieuXuatDialogAdd_Controller(this);
        tableChonSach.getSelectionModel().addListSelectionListener(selection);
        tableChonSach.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Đảm bảo mỗi lần chỉ chọn đc 1 row
        tableListBan.getSelectionModel().addListSelectionListener(selection);
        tableListBan.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Đảm bảo mỗi lần chỉ chọn đc 1 row

        ActionListener action=new PhieuXuatDialogAdd_Controller(this);
        btnThemChiTiet.addActionListener(action);
        btnSua.addActionListener(action);
        btnXoaV2.addActionListener(action);
        BtnXoaAllV2.addActionListener(action);
        
//        pack();
        setSize(1200,550);
        setLocationRelativeTo(null);
        setVisible(true);
        
    }// </editor-fold>                        

//    private void txfSoLuongActionPerformed(java.awt.event.ActionEvent evt) {                                           
//        // TODO add your handling code here:
//    }                                          
//
//    private void txfGiaBanActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        // TODO add your handling code here:
//    }                                         

    private void btnThemPhieuActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txfSoLuongV2ActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txfTimKhachActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txfNhanVienActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void txfSDTActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }  
    public String getTxfTimSachText(){
        return txfTimSach.getText();
    }
    public JTextField getTxfTimKhach(){
        return txfTimKhach;
    }
    public JTextField getTxfTimSach(){
        return txfTimSach;
    }
    public void setTxfDonGia(String giaban){
        this.txfGiaBan.setText(giaban);
    }
    public JTable getTableChonSach(){
        return tableChonSach;
    }
    public JTextField getTxfKhachHang(){
        return txfKhachHang;
    }
    public JTextField getTxtSoLuong(){
        return txfSoLuong;
    }
    public JTextField gettTxfDonGia(){
        return txfGiaBan;
    }
    public DefaultTableModel getDataBan(){
        return dataBan;
    }
    public JTable getTableListBan(){
        return tableListBan;
    }
    public JTextField getTxfTenSachV2() {
        return txfTenSachV2;
    }
    public JTextField getTxfSoLuongV2() {
        return txfSoLuongV2;
    }
    public JTextField getTxfDonGiaV2() {
        return txfDonGiaV2;
    }
    public JTextField getTxfThanhTienV2() {
        return txfThanhTienV2;
    }
    public JTextField getTxfTongTien() {
        return txfTongTien;
    }
    public JTextField getTxfGiamGia() {
        return txfGiamGia;
    }
    public JTextField getTxfThanhToan() {
        return txfThanhToan;
    }
    
    
    // Show các số điện thoại
    public void ShowSDT(){
        popupMenuSDT.setVisible(false); // Ẩn popup trước khi cập nhật
        popupMenuSDT.removeAll();
        String input = txfTimKhach.getText();
        if (input.isEmpty()) return; // Không hiển thị nếu không có input
        boolean find = false;
       for (int i = 0; i < dataSDT.getSize(); i++) { // Duyệt qua DefaultListModel
            String phone = dataSDT.getElementAt(i);
            if(phone.startsWith(input)){
                JMenuItem item=new JMenuItem(phone);
                item.addActionListener(e -> {
                    txfTimKhach.setText(phone); // Chọn số vào text field
                    popupMenuSDT.setVisible(false);
                });
                popupMenuSDT.add(item);
                find = true;
            }
        
        }
       if(find){
           popupMenuSDT.show(txfTimKhach, 0, txfTimKhach.getHeight());
           // Giữ focus trên textField để nhập tiếp mà không bị mất focus
           // Kiểm tra xem txfTimKhach có đang được focus không
            if (txfTimKhach.isFocusOwner()) {
                SwingUtilities.invokeLater(() -> txfTimKhach.requestFocusInWindow());
        }

       }
    } 
    // Nhập SDT xong nó hiện thông tin
    public void showNameKhandSDT(){
        String sdt=txfTimKhach.getText().trim();
        if(hashMapKh.containsKey(sdt)){
            txfKhachHang.setText(hashMapKh.get(sdt));
            txfSDT.setText(sdt);
        }
    }
    // Tìm sách bằng Document
    public void FindBook(String text){
        listSach=new SachBUS().search(text);
        dataBook.setRowCount(0);
        for(SachDTO s: listSach){
            // Tìm tác giả
            String tentg="";
            TacGiaDTO tg=tacgiaBUS.getTGById(s.getMatacgia());
            tentg=tg.getHotentacgia();
            dataBook.addRow(new Object[]{s.getMasach(),s.getTensach(),tentg,s.getSoluongton()});
        }
    }
    // Update tiền cần thanh toán
    public void CalcBill(){
        int tongtien=0;
        int giamgia;
        int thanhtoan=0;
        int columnTong=3;
        for (int i=0;i<tableListBan.getRowCount();i++){
            tongtien+= Integer.parseInt(tableListBan.getValueAt(i, columnTong).toString());
        }
        txfTongTien.setText(String.valueOf(tongtien));
        if(txfGiamGia.getText().isEmpty()){
            giamgia=0;
        }else{ giamgia=Integer.parseInt(txfGiamGia.getText().toString());}
        thanhtoan=tongtien-giamgia;
        txfThanhToan.setText(thanhtoan+"");
    }
    // Hàm kiêm tra nếu Table bên Danh sách bán =0 thì set các txf chỉnh sửa về rỗng
    public boolean CheckEmptyRow(){
        if(tableListBan.getRowCount()==0){
            return  true;
        }
        return false;
    }

    

    
}
